# disable autofixing PRs, commenting "pre-commit.ci autofix" on a pull request triggers a autofix
ci:
    autofix_prs: false

exclude: ^conda_lock/_vendor/.*$

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
    exclude: "^.*\\.patch$"
  - id: check-ast

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.0
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    additional_dependencies:
      - pydantic
      - pytest
      - types-colorama
      - types-filelock
      - types-freezegun
      - types-requests
      - types-pygments
      - types-pyyaml
      - types-setuptools
      - types-toml
    exclude: ^(tests/test-local-pip/setup.py$|tests/test_conda_lock.py)
